name: Rust PR

on:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        target: [aarch64-apple-darwin, x86_64-unknown-linux-gnu]
        exclude:
        - os: ubuntu-latest
          target: aarch64-apple-darwin
        - os: macos-latest
          target: x86_64-unknown-linux-gnu
    env:
      CARGO_TERM_COLOR: always
      RUSTFLAGS: ${{ matrix.target == 'x86_64-unknown-linux-gnu' && '-C link-arg=-Wl,--as-needed' || '' }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        profile: minimal
        override: true
    - name: Lint
      run: cargo clippy --all-targets -- -D warnings
    - name: Test
      run: cargo test --target ${{ matrix.target }}
    - name: Format
      run: cargo fmt --all -- --check
    - name: Build
      run: cargo build --release --target ${{ matrix.target }}
